In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([5,6,7])

c = np.array([3,4])

print(a+b)
print(3 * a)
print(np.dot(a,b))

print(np.linalg.norm(c))



[ 6  8 10]
[3 6 9]
38
5.0


In [6]:
a = np.array([[1,2] , [3,4]])
b = np.array([[5,6] , [7,8]])

print(np.dot(a,b))

print(a * b)


[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


In [12]:
x = np.array([1,0,-1])
w = np.array([[1 , 2 , 3] , [4 , 5 , 6]])

print(np.dot(w,x))
print( a . T)
print(np.eye(3))
print(a.shape)

[-2 -2]
[[1 3]
 [2 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(2, 2)


In [14]:
a = np.array([[2,1],[1,2]])
values, vectors = np.linalg.eig(a)

print(values)
print(vectors)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [15]:
v = vectors [: , 0]
print ( a @ v ) 
print ( values [0] * v )

[2.12132034 2.12132034]
[2.12132034 2.12132034]


In [20]:
import numpy as np
rng = np.random.default_rng(0)
# Estimate P ( even ) on a die by si mu la ti on
rolls = rng.integers (1 , 7 , size =100_000 )
print ( np.mean ( rolls % 2 == 0) ) # ~0.5

d1 = rng.integers (1 , 7 , size =100_000 )
d2 = rng.integers (1 , 7 , size =100_000 )
print ( np.mean ( d1 + d2 == 7) )

0.49758
0.16774
